name = "os4web"
compatibility_date = "2024-09-25"

# Specify the directory to deploy
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "os4web"
id = "57d98f4e2f544fb0894a1082c11c417a"

